
management:
  endpoint:
    health:
      show-details: never
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: info,health,prometheus
server:
  port: 8079


template:
  # 模板: MEM -字符串  FILE -文件
  mode: MEM
  # FILE模式下存在模板的目录
  template-path: ./templates

logging:
  level:
    cn.karent: DEBUG

